### PR TITLE
Backport of #1009

### PR DESCRIPTION
**Pull request by Hawkeye1909**
Title says it all...

### CODE REVIEW

**Comment by tomasnorre** [comment]
Thanks a lot, would you mind updating the README.md too?

**Comment by Hawkeye1909** [comment]
> Thanks a lot, would you mind updating the README.md too?

What should be updated there?

**Comment by tomasnorre** [comment]
> > Thanks a lot, would you mind updating the README.md too?
> 
> What should be updated there?
Sorry, meant the CHANGELOG.md

**Comment by Hawkeye1909** [comment]
> Sorry, meant the CHANGELOG.md

I've finally got round to doing this.

**Pull request merged**
