### PR TITLE
[TASK] Fix CSS class for select item in backend module

### PR DESCRIPTION
**Pull request by derhansen**

### CODE REVIEW

**Comment by tomasnorre** [comment]
I don't get why all the tests are red, your change should have nothing to do with that. 

Can I get you to add a comment to the CHANGELOG.md just for triggering a new build, don't know if anything timed out before I approved the workflow.

**Comment by derhansen** [comment]
Maybe problems with testing framework. There was just released a news version recently - see https://github.com/TYPO3/testing-framework/releases/tag/8.1.1

**Comment by tomasnorre** [comment]
It works locally with the 8.1.1 tag with both PHP 8.1 and 8.3, so I don't think that's the problem. I have merged your change as it cannot break anything besides layout.

**Comment by tomasnorre** [comment]
Strange it worked in the merge to main. https://github.com/tomasnorre/crawler/actions/runs/9623324396/job/26545650109

**Pull request merged**
