### PR TITLE
[BUGFIX] Add new middleware for content finish

### PR DESCRIPTION
**Pull request by tomasnorre**
This middleware splits the content from the Crawler Initialization Middleware
to ensure that the content is written at the end.

This ensures that middleware that expects response-object gets the content
for the renders and the crawler queue gets the correct request status.

Resolves: #729

**I have**

- [x] Checked that CGL are followed
- [x] Checked that the Tests are still working
- [x] Added description to CHANGELOG.md (github-handle is optional)
- [ ] Added tests for the new code

### CODE REVIEW

**Comment by tomasnorre** [comment]
@CDRO I could not assign you as reviewer, would you mind looking at the PR?

**Comment by CDRO** [comment]
@tomasnorre Looks good to me!

**Comment by tomasnorre** [comment]
Hi @lochmueller,

I was just looking into stalled PRs, could this perhaps be the solution that would also solve the problem the crawler is causing for the Staticfilecache? 

I would be happy to hear you feedback.

**Comment by lochmueller** [comment]
Hey @tomasnorre 
This move "the problem" just up in the middleware stack, so StaticFileCache would work. But it still detroy the middleware stack, because a "new response" is created. I send a new pull request incl. a better solution in a few minutes...
Regards,
Tim

**Comment by tomasnorre** [comment]
Closed with #1018

**Pull request closed without merging**
