### PR TITLE
Fix: ProcessQueue throws truncated incorrect decimal value

### PR DESCRIPTION
**Pull request by xyng**
## Description

This PR provides a test and fix for #1082 - changes the param-type of `processId` in the prepared statement to `string` instead of `integer`, since the database field already uses `varchar(50)` and `ProcessQueueCommand` will pass a string.
That can lead to either non-matches (sqlite) or even runtime errors (in one of our environments using MariaDB).

**I have**

- [x] Checked that CGL are followed
- [x] Checked that the Tests are still working
- [x] Added description to CHANGELOG.md (github-handle is optional)
- [ ] Added tests for the new code

## Note

@tomasnorre I tried my best to get the test to reproduce. For some reason, only the SQLite one ran on my machine. For SQLite, there is no runtime error, but non-numeric values are not matched, leading the test case to fail the count-check which is somewhat sufficient to evaluate the problem.
I'd appreciate if you could check the MySQL and PostgreSQL derivates if they work correctly (either throw and exception or at least fail the count test).

### CODE REVIEW

**Comment by tomasnorre** [comment]
@xyng Thank you so much for your contribution. Looks good at first glance. Will have the CI check the MySQL, MariaDB and PostgreSQL for us ;) 

There are some code-style, use statement sorting not right atm, but I think that is due to a rector update that isn't caused by you. So don't worry about those if the pipeline turns red.

**Comment by xyng** [comment]
@tomasnorre thank you for checking and your feedback!
I have added an entry to the changelog - not entirely sure about the wording.

**Comment by tomasnorre** [comment]
> @tomasnorre thank you for checking and your feedback! I have added an entry to the changelog - not entirely sure about the wording.

The wording is fine. :)

**Comment by tomasnorre** [comment]
@xyng Thanks for your contribution, cannot say when it will be released.

**Comment by graphicfox** [comment]
Hello, is there any update when this will be released? My scheduler task never runs because of this error. :(

**Comment by tomasnorre** [comment]
Hi.. 

I can make a release some when next week. Just need a little preparation.

**Pull request merged**
