### PR TITLE
Related #837 - use header instead of content for meta information

### PR DESCRIPTION
**Pull request by lochmueller**
## Description

My idea to solve this problem: Please double check this. Didn't test it in detail.
https://github.com/tomasnorre/crawler/issues/837

### CODE REVIEW

**Comment by tomasnorre** [comment]
I have fixed the tests this morning, could you please rebase your `fix-middleware-stack` branch based on my branch with the same name. I didn't manage to push to have the changes within the same PR.

**Comment by lochmueller** [comment]
Done. I fast-forward merge your changes into this PR

**Comment by tomasnorre** [comment]
Thanks. I'll have this tested tomorrow. But from the code it looks gode.

**Comment by tomasnorre** [comment]
I have tested this now, and everything works like I expected. StaticFileCache with NoCrawl like

```php
class NoCrawlerCall extends AbstractRule
{
    public function checkRule(ServerRequestInterface $request, array &$explanation, bool &$skipProcessing): void
    {
        $crawlerInformation = $request->getHeaderLine('X-T3CRAWLER') ?? null;
        if (!empty($crawlerInformation)) {
            // @todo find another solution to cache content via Crawler (avoid caching the status JSON)
            // @see https://github.com/lochmueller/staticfilecache/issues/260
            //$explanation[__CLASS__] = 'It is a Crawler configuration call, that should not cached by SFC';
            //$skipProcessing = true;
        }
    }
}
```

Let the crawler also fill the StaticFileCache. 

My suggestion would be, that your next release conflicts with `tomasnorre/crawler` 11.0.0 or lower, to ensure that people are updating to the compatible crawler version. 

Thanks a lot for your help with this. Really appreciated.

**Review by tomasnorre — APPROVED** [review]

**Pull request merged**
